[project]
name = ""
version = ""
description = ""
authors = [
    {name = "francisco miranda", email = "fmirchav@umag.cl"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

